/****************************************************************/
/* MESSAGE.H header for the message functions                   */
/****************************************************************/

/****************************************************************/
/* Function prototypes                                          */
/****************************************************************/

MRESULT CreateProc (HWND, ULONG, MPARAM, MPARAM) ;
VOID DestroyProc (HWND) ;
VOID Button1Proc (HWND, MPARAM) ;
VOID SizeProc (HWND, MPARAM) ;
VOID PaintProc (HWND) ;
VOID CommandProc (HWND, MPARAM) ;
VOID InitMenuProc (HWND, MPARAM) ;
