/****************************************************************/
/*  WINPROCS.H header for the window procedures                 */
/****************************************************************/

/****************************************************************/
/*  Function prototypes                                         */
/****************************************************************/

MRESULT EXPENTRY wpClientWndProc (HWND, ULONG, MPARAM, MPARAM) ;
MRESULT EXPENTRY wpInfoDlgProc (HWND, ULONG, MPARAM, MPARAM) ;
MRESULT EXPENTRY wpBetDlgProc (HWND, ULONG, MPARAM, MPARAM) ;
MRESULT EXPENTRY wpNewDlgProc (HWND, ULONG, MPARAM, MPARAM) ;
MRESULT EXPENTRY wpSettingsDlgProc (HWND, ULONG, MPARAM, MPARAM) ;
MRESULT EXPENTRY wpMarkerDlgProc (HWND, ULONG, MPARAM, MPARAM) ;
MRESULT EXPENTRY wpNumericEntry (HWND, ULONG, MPARAM, MPARAM) ;
